production:
  host: mysql.georgetowncied.org
  database: cied_production
  username: cied_production
  password: 'tAt-jeuS-shU-Dac-phe'
staging:
  host: mysql.georgetowncied.org
  database: cied_staging
  username: cied_staging
  password: 'mIv-noG-Owd-or-Ib-Ye'
dev:
  host: mysql.georgetowncied.org
  database: cied_staging
  username: cied_staging
  password: 'mIv-noG-Owd-or-Ib-Ye'
